alacritty_background = "%background"
alacritty_foreground = "%foreground"

alacritty_text = "%text"
alacritty_cursor = "%cursor"
alacritty_black = "%black"
alacritty_red = "%red"
alacritty_green = "%green"
alacritty_yellow = "%yellow"
alacritty_blue = "%blue"
alacritty_magenta = "%magenta"
alacritty_cyan = "%cyan"
alacritty_white = "%white"

alacritty_light_black = "%light_black"
alacritty_light_red = "%light_red"
alacritty_light_green = "%light_green"
alacritty_light_yellow = "%light_yellow"
alacritty_light_blue = "%light_blue"
alacritty_light_magenta = "%light_magenta"
alacritty_light_cyan = "%light_cyan"
alacritty_light_white = "%light_white"
