dotfiles_dir = "dotfiles"
gpg_user_id = "paul.delafosse@protonmail.com"

[settings]
hooks = ["sway reload"]
vars = [
    "bombadil/themes/sweay.toml",
    "bombadil/vars.toml",
]

[settings.dots]
alacritty = { source = "alacritty", target = ".config/alacritty" }
wofi = { source = "wofi", target = ".config/wofi" }
onagre = { source = "onagre", target = ".config/onagre" }
nwg = { source = "nwg-launchers", target = ".config/nwg-launchers" }
sway = { source = "sway", target = ".config/sway" }
sway_start = { source = "start.sh", target = "start.sh" }
waybar = { source = "waybar", target = ".config/waybar" }
kanshi = { source = "kanshi", target = ".config/kanshi" }
mako = { source = "mako", target = ".config/mako" }
zsh = { source = "zsh/zshrc", target = ".zshrc" }
zsh_env = { source = "zsh/zshenv", target = ".zshenv" }
starship = { source = "zsh/starship.toml", target = ".config/starhip.toml" }
git = { source = "git/gitconfig", target = ".gitconfig" }
vim = { source = "nvim/init.vim", target = ".vimrc" }
nvim = { source = "nvim", target = ".config/nvim" }
illumination = { source = "illumination", target = ".config/illumination" }
neofetch = { source = "neofetch", target = ".config/neofetch" }
beets = { source = "beets", target = ".config/beets" }
ncmpcpp = { source = "ncmpcpp", target = ".ncmpcpp" }
mdp = { source = "mpd", target = ".config/mpd" }
gpg_agent = { source = "gpg/gpg-agent.conf", target = ".gnupg/gpg-agent.conf" }
maven = { source = "maven/settings.corporate.xml", target = ".m2/settings.xml" }
xdg_dirs = { source = "xdg/user-dirs.dirs", target = ".config/user-dirs.dirs" }
gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
gtk3 = { source = "gtk/gtk-3.0", target = ".config//gtk-3.0" }


## Work in progress 
## Still need to templatize some dots
[profiles.argonaut]
vars = [ "bombadil/themes/argonaut.toml" ]

[profiles.argonaut.dots]
alacritty = { source="earzear"}

[profiles.ayu_dark]
vars = [ "bombadil/themes/ayu_dark.toml" ]

[profiles.base16_default_dark]
vars = [ "bombadil/themes/base16_default_dark.toml" ]

[profiles.campbell]
vars = [ "bombadil/themes/campbell.toml" ]

[profiles.challenger_deep]
vars = [ "bombadil/themes/challenger_deep.toml" ]

[profiles.Cobalt2]
vars = [ "bombadil/themes/Cobalt2.toml" ]

[profiles.cyber_punk_neon]
vars = [ "bombadil/themes/cyber_punk_neon.toml" ]

[profiles.darcula]
vars = [ "bombadil/themes/darcula.toml" ]

[profiles.dracula]
vars = [ "bombadil/themes/dracula.toml" ]

[profiles.falcon]
vars = [ "bombadil/themes/falcon.toml" ]

[profiles.gotham]
vars = [ "bombadil/themes/gotham.toml" ]

[profiles.gruvbox_dark]
vars = [ "bombadil/themes/gruvbox_dark.toml" ]

[profiles.gruvbox_light]
vars = [ "bombadil/themes/gruvbox_light.toml" ]
