dotfiles_dir = "dotfiles"


[[var]]
path = "themes/argonaut.toml"


[[dot]]
source = "alacritty"
target = ".config/alacritty"

[[dot]]
source = "wofi"
target = ".config/wofi"

[[dot]]
source = "sway"
target = ".config/sway"

[[dot]]
source = "kanshi"
target = ".config/kanshi"

[[dot]]
source = "mako"
target = ".config/mako"

[[dot]]
source = "zsh/zshrc"
target = ".zshrc"

[[dot]]
source = "zsh/zprofile"
target = ".zprofile"

[[dot]]
source = "git/gitconfig"
target = ".gitconfig"

[[dot]]
source = "nvim/init.vim"
target = ".vimrc"

[[dot]]
source = "nvim"
target = ".config/nvim"

[[dot]]
source = "illumination"
target = ".config/illumination"

[[dot]]
source = "ncmpcpp"
target = ".ncmpcpp"

[[dot]]
source = "neofetch"
target = ".config/neofetch"

[[hook]]
command = "echo hello world"

[[hook]]
command = "pouet"

[[hook]]
command = "echo hello world"
