bar_urgent = "%light_red"
bar_clock_bg = "%light_white"
bar_clock_fg = "%black"
battery_bg = "%magenta"
battery_fg = "%black"
battery_charging_fg = "#ffffff"
battery_charging_bg = "#26A65B"
battery_critical_not_charging_fg= "#ffffff"
battery_critical_not_charging_bg="#f53c3c"
blink_bg = "#ffffff"
blink_fg = "#000000"
label_focused = "#000000"
cpu_bg = "#2ecc71"
cpu_fg = "#000000"
mem_bg = "#9b59b6"
backlight_bg = "#90b1b1"
network_bg = "#2980b9"
network_disconnected = "#f53c3c"
pulse_audio_bg = "%yellow"
pulse_audio_fg = "%black"
pulse_audio_muted_bg = "#90b1b1"
temperature_bg = "%light_yellow"
temperature_critical_bg = "%red"
tray_bg = "%light_blue"
idle_inibitor_bg = "#2d3436"
idle_inibitor_bg_activated = "#ecf0f1"
