alacritty_background = "#2E3440"
alacritty_foreground = "#D8DEE9"

alacritty_text = "#2E3440"
alacritty_cursor = "#D8DEE9"
alacritty_black = "#3B4252"
alacritty_red = "#BF616A"
alacritty_green = "#A3BE8C"
alacritty_yellow = "#EBCB8B"
alacritty_blue = "#81A1C1"
alacritty_magenta = "#B48EAD"
alacritty_cyan = "#88C0D0"
alacritty_white = "#E5E9F0"

alacritty_light_black = "#4C566A"
alacritty_light_red = "#BF616A"
alacritty_light_green = "#A3BE8C"
alacritty_light_yellow = "#EBCB8B"
alacritty_light_blue = "#81A1C1"
alacritty_light_magenta = "#B48EAD"
alacritty_light_cyan = "#8FBCBB"
alacritty_light_white = "#ECEFF4"
