background= "#202734"
cursor= "#202734"
foreground= "#CBCCC6"
text= "#CBCCC6"
black= "#191E2A"
red= "#FF3333"
green= "#BAE67E"
yellow= "#FFA759"
blue= "#73D0FF"
magenta= "#FFD580"
cyan= "#95E6CB"
white= "#C7C7C7"

light_black= "#686868"
light_red= "#F27983"
light_green= "#A6CC70"
light_yellow= "#FFCC66"
light_blue= "#5CCFE6"
light_magenta= "#FFEE99"
light_cyan= "#95E6CB"
light_white= "#FFFFFF"