light_black = "#696969"
light_blue = "#007FFF"
light_cyan = "#00CCCC"
light_green = "#03C03C"
light_magenta = "#FF1493"
light_red = "#FF2400"
light_white = "#FFFAFA"
light_yellow = "#FDFF00"

black = "#10100E"
blue = "#0087BD"
cyan = "#20B2AA"
green = "#009F6B"
magenta = "#9A4EAE"
red = "#C40233"
white = "#C6C6C4"
yellow = "#FFD700"

cursor = "#d8d8d8"
text = "#d8d8d8"
background = "#10100E"
foreground = "#C6C6C4"

