light_black = "#767676"
light_blue = "#3b78ff"
light_cyan = "#61d6d6"
light_green = "#16c60c"
light_magenta = "#b4009e"
light_red = "#e74856"
light_white = "#f2f2f2"
light_yellow = "#f9f1a5"

black = "#0c0c0c"
blue = "#0037da"
cyan = "#3a96dd"
green = "#13a10e"
magenta = "#881798"
red = "#c50f1f"
white = "#cccccc"
yellow = "#c19c00"

cursor = "#d8d8d8"
text = "#d8d8d8"
background = "#0c0c0c"
foreground = "#cccccc"

