light_black = "#282a35"
light_blue = "#caa9fa"
light_cyan = "#9aedfe"
light_green = "#5af78e"
light_magenta = "#ff92d0"
light_red = "#ff6e67"
light_white = "#e6e6e6"
light_yellow = "#f4f99d"

black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

cursor = "#0abdc6"
text = "#000b1e"
background = "#282a36"
foreground = "#f8f8f2"

