########################
### ALACRITTY COLORS ### 
########################
alacritty_background = "#292C3E"
alacritty_foreground = "#EBEBEB"

alacritty_text = "text"
alacritty_cursor = "cursor"
alacritty_black = "black"
alacritty_red = "red"
alacritty_green = "green"
alacritty_yellow = "yellow"
alacritty_blue = "blue"
alacritty_magenta = "magenta"
alacritty_cyan = "cyan"
alacritty_white = "white"

alacritty_light_black = "light_black"
alacritty_light_red = "light_red"
alacritty_light_green = "light_green"
alacritty_light_yellow = "light_yellow"
alacritty_light_blue = "light_blue"
alacritty_light_magenta = "light_magenta"
alacritty_light_cyan = "light_cyan"
alacritty_light_white = "light_white"

########################
####  SWAY COLORS   ####
########################

client_focused_border = "yellow"    
client_focused_background = "background"    
client_focused_text = "text"    
client_focused_indicator = "blue"     
client_focused_child_border = "magenta"

client_focused_inactive_border = "light_white"      
client_focused_inactive_background = "background"
client_focused_inactive_text = "text"   
client_focused_inactive_indicator= "light_black"     
client_focused_inactive_child_border = "light_white"

client_unfocused_border = "light_white"     
client_unfocused_background = "background"      
client_unfocused_text = "text"    
client_unfocused_indicator = "light_black"     
client_unfocused_child_border = "light_white"

client_urgent_border = "red"  
client_urgent_background = "background"      
client_urgent_text = "text"    
client_urgent_indicator = "light_black"     
client_urgent_child_border = "light_white"

########################
##### WOFI COLORS  #####
########################

wofi_bg = "magenta"
wofi_input_bg = "magenta"


########################
#### WAYBAR COLORS  ####
########################

bar_urgent = "#FF4352"
bar_clock_bg = "#64727D"
battery_bg = "#ffffff"
battery_fg = "#000000"
battery_charging_fg = "#ffffff"
battery_charging_bg = "#26A65B"
battery_critical_not_charging_fg= "#ffffff"
battery_critical_not_charging_bg="#f53c3c"
blink_bg = "#ffffff"
blink_fg = "#000000"
label_focused = "#000000"
cpu_bg = "#2ecc71"
cpu_fg = "#000000"
mem_bg = "#9b59b6"
backlight_bg = "#90b1b1"
network_bg = "#2980b9"
network_disconnected = "#f53c3c"
pulse_audio_bg = "#f1c40f"
pulse_audio_fg = "#000000"
pulse_audio_muted_bg = "#90b1b1"
temperature_bg = "#f0932b"
temperature_critical_bg = "#eb4d4b"
tray_bg = "#2980b9"
idle_inibitor_bg = "#2d3436"
idle_inibitor_bg_activated = "#ecf0f1"


########################
##### WOB COLORS   #####
########################

wob_bg_color = "#FF1BA6FA"
wob_bar_color = "#FFA578EA"
wob_border_color = "#FF6D7070"
