# General (based on alacrity config)
background = "#292C3E"
foreground = "#EBEBEB"

text = "#FF261E"
cursor = "#FF261E"
black = "#0d0d0d"
red = "#FF301B"
green = "#A0E521"
yellow = "#FFC620"
blue = "#1BA6FA"
magenta = "#8763B8"
cyan = "#21DEEF"
white = "#EBEBEB"

light_black = "#6D7070"
light_red = "#FF4352"
light_green = "#B8E466"
light_yellow = "#FFD750"
light_blue = "#1BA6FA"
light_magenta = "#A578EA"
light_cyan = "#73FBF1"
light_white = "#FEFEF8"

# Bar 

bar_urgent = "#FF4352"
bar_clock_bg = "#64727D"
battery_bg = "#ffffff"
battery_fg = "#000000"
battery_charging_fg = "#ffffff"
battery_charging_bg = "#26A65B"
battery_critical_not_charging_fg= "#ffffff"
battery_critical_not_charging_bg="#f53c3c"
blink_bg = "#ffffff"
blink_fg = "#000000"
label_focused = "#000000"
cpu_bg = "#2ecc71"
cpu_fg = "#000000"
mem_bg = "#9b59b6"
backlight_bg = "#90b1b1"
network_bg = "#2980b9"
network_disconnected = "#f53c3c"
pulse_audio_bg = "#f1c40f"
pulse_audio_fg = "#000000"
pulse_audio_muted_bg = "#90b1b1"
temperature_bg = "#f0932b"
temperature_critical_bg = "#eb4d4b"
tray_bg = "#2980b9"
idle_inibitor_bg = "#2d3436"
idle_inibitor_bg_activated = "#ecf0f1"


# Wob
wob_bg_color = "#FF1BA6FA"
wob_bar_color = "#FFA578EA"
wob_border_color = "#FF6D7070"
