light_black = "#555555"
light_blue = "#caa9fa"
light_cyan = "#8be9fd"
light_green = "#50fa7b"
light_magenta = "#ff79c6"
light_red = "#ff5555"
light_white = "#ffffff"
light_yellow = "#f1fa8c"

black = "#000000"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bbbbbb"
yellow = "#f1fa8c"

cursor = "#0abdc6"
text = "#000b1e"
background = "#282a36"
foreground = "#f8f8f2"

