light_black = "#928374"
light_blue = "#83a598"
light_cyan = "#8ec07c"
light_green = "#b8bb26"
light_magenta = "#d3869b"
light_red = "#fb4934"
light_white = "#ebdbb2"
light_yellow = "#fabd2f"

black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

cursor = "#ffe8c0"
text = "#020221"
background = "#282828"
foreground = "#ebdbb2"

