light_black = "#928374"
light_blue = "#076678"
light_cyan = "#427b58"
light_green = "#79740e"
light_magenta = "#8f3f71"
light_red = "#9d0006"
light_white = "#3c3836"
light_yellow = "#b57614"

black = "#fbf1c7"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#7c6f64"
yellow = "#d79921"

cursor = "#ffe8c0"
text = "#020221"
background = "#fbf1c7"
foreground = "#3c3836"

