light_black = "#000000"
light_blue = "#0000ff"
light_cyan = "#00ffff"
light_green = "#00ff00"
light_magenta = "#ff00ff"
light_red = "#ff0000"
light_white = "#ffffff"
light_yellow = "#ffff00"

black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

cursor = "#ffffff"
text = "#aaaaaa"
background = "#444444"
foreground = "#dddddd"

