light_black = "#5b5858"
light_blue = "#3fc4de"
light_cyan = "#6be4e6"
light_green = "#3fdaa4"
light_magenta = "#f075b5"
light_red = "#ec6a88"
light_white = "#d5d8da"
light_yellow = "#fbc3a7"

black = "#16161c"
blue = "#26bbd9"
cyan = "#59e1e3"
green = "#29d398"
magenta = "#ee64ac"
red = "#e95678"
white = "#d5d8da"
yellow = "#fab795"

cursor = "#ffffff"
text = "#aaaaaa"
background = "#1c1e26"
foreground = "#e0e0e0"

