light_black = "#808080"
light_blue = "#0066ff"
light_cyan = "#00ffff"
light_green = "#33ff00"
light_magenta = "#cc00ff"
light_red = "#fe0100"
light_white = "#FFFFFF"
light_yellow = "#feff00"

black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

cursor = "#ffffff"
text = "#F81CE5"
background = "#000000"
foreground = "#ffffff"

