
bg = "%red"
input_bg = "%red"
input_color = "%red" 
input_focused_bg = "%red"
input_focused_border = "%red"
input_focused_color = "%red" 
input_focused_border_color = "%red"
inner_box_bg = "%red" 
inner_box_flowchild_bg = "%red"
inner_box_flowchild_focused_bg = "%red"
outer_box_bg = "%red"
text_bg = "%red"
text = "%black"
scroll = "%red"
